# Generated by Django 3.1.7 on 2021-03-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('file_uploaded', models.FileField(upload_to='Files')),
            ],
        ),
    ]
