# Generated by Django 3.1.7 on 2021-03-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='compaint_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
