# Generated by Django 3.1.7 on 2021-03-09 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20210309_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='compaint_number',
            new_name='complaint_number',
        ),
    ]
