# Generated by Django 3.1.7 on 2021-03-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210309_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_test',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
