# Generated by Django 3.1.7 on 2021-03-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_complaint_complaint_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_test',
            new_name='complaint_text',
        ),
    ]
